sudo: false
language: python
matrix:
  include:
    - dist: xenial
      python: "3.9"
      env: TOXENV=py39
      after_success: coveralls
    - os: osx
      language: generic
      env:
        - PYTHON=3.9.0
        - TOXENV=py39

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi
install: pip install tox-travis coveralls
script: |
  make test
